[workspace]
resolver = "2"

members = [
    "crates/auth", 
    "crates/database",
    "crates/models",
    "crates/service",
    "crates/repository",

    "apps/api"
]

[workspace.dependencies]
axum = "0.8.9"
tokio = { version = "1.53.0", features = ["full"] }
sqlx =  { version = "0.9", features = ["runtime-tokio", "postgres", "macros"]}
envy = "0.4.2"
serde = { version = "1.0.229", features = [ "derive" ]}
dotenvy = "0.15.7"
bcrypt = "0.19.3"